services:
  db:
    build: ./couchbase
    container_name: db
    environment:
      - COUCHBASE_USER=admin
      - COUCHBASE_PASSWORD=password
      - COUCHBASE_BUCKET=todo-bucket
    volumes:
      - ~/couchbase/node1:/opt/couchbase/var
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 11210:11210

  todo_server:
    build: .
    container_name: todo-app
    environment:
      COUCHBASE_HOST: db
    depends_on:
      - db
    ports:
      - 8080:8080

#secrets:
#  couchbase_secrets:
#    file: ./couchbase/secrets/couchbase_secrets.txt